name:                german1608-github-io
version:             0.0.1
github:              "german1608/german1608-github-io"
license:             BSD3
author:              "Germán Robayo"
maintainer:          "germanrobayo33@gmail.com"
copyright:           "2020 Germán Robayo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         My personal website, <https://github.com/german1608/german1608-github-io#readme>

dependencies:
- base >= 4.7 && < 5
- hakyll >= 4.13.3.0

library:
  source-dirs: src
  ghc-options:
  - -Wall
